# ->->->->-> Primary <-<-<-<-<-
arch: "vgg16_bn_ARLST"
exp_name: "VGG"
result_dir: "./trained_models"
num_classes: 10
exp_mode: "prune"
layer_type: "arlst"
init_type: "kaiming_normal"
train_attack_methods: "pgd"
test_attack_methods: "pgd"

# ->->->->-> Pruning <-<-<-<-<-
k: 0.5


# ->->->->-> Train <-<-<-<-<-
trainer: "adv"
epochs: 100
optimizer: "sgd"
lr: 0.005
lr_schedule: "cosine"
wd: 0.0007
momentum: 0.9
#warmup
warmup_epochs: 0
warmup_lr: 0.1



# ->->->->-> Eval <-<-<-<-<-
val_method: "adv"


# ->->->->-> Dataset <-<-<-<-<-
dataset: CIFAR10
batch_size: 256
test_batch_size: 128
data_dir: "./datasets"
data_fraction: 1.0

# ->->->->-> Adv <-<-<-<-<-
epsilon: 0.031
num_steps: 10
step_size: 0.0078
clip_min: 0
clip_max: 1
distance: "l_inf"
beta: 6.0


# ->->->->-> Misc <-<-<-<-<-
gpu: "3"
seed: 1234
print_freq: 10